export type McpAuthScheme = "bearer" | "basic" | "custom-header" | "github-app";

export type McpTemplateOptions = {
  name: string;
  urlEnv: string;
  tokenEnv: string;
  description: string;
  tools: string[];
  scheme?: McpAuthScheme;     // default "bearer"
  headerName?: string;        // used when scheme === "custom-header"
};

/** Pure: render the TypeScript source for a read-only, env-token MCP connection. */
export function renderMcpConnection(opts: McpTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  const url = `process.env[${JSON.stringify(opts.urlEnv)}] || "https://example.invalid/mcp"`;
  const tokenExpr = `process.env[${JSON.stringify(opts.tokenEnv)}] || ""`;
  const scheme = opts.scheme ?? "bearer";

  // Most schemes reuse the same <PREFIX>_MCP_URL + <PREFIX>_MCP_TOKEN pair; only the
  // way the token becomes a header differs, so the config entry, .env.example, and
  // stub renderer stay identical across them. The `github-app` scheme is the exception:
  // it mints a short-lived installation token from GITHUB_APP_* (no <PREFIX>_MCP_TOKEN),
  // so it appends an extra import — hence `imports` is a mutable accumulator, not a
  // hard-coded first line.
  let imports = `import { defineMcpClientConnection } from "eve/connections";`;
  // The generated file's header comment. Env-token schemes (bearer/basic/custom-header)
  // keep the original wording; github-app overrides it below because that file mints a
  // GitHub App installation token (not an env token) and is typically a WRITE connection —
  // and these files get committed into consumer repos, so the header must be accurate.
  let header = "// Generated by `deskmate mcp-add`. Read-only, env-token (single-deployment).";
  let credLine: string;
  let hint: string;
  if (scheme === "basic") {
    // Token env holds plaintext "publicKey:secretKey"; base64-encode it at runtime.
    credLine = `  headers: { Authorization: \`Basic \${Buffer.from(${tokenExpr}).toString("base64")}\` },`;
    hint = `// Set ${opts.urlEnv} + ${opts.tokenEnv} (plaintext "publicKey:secretKey", base64-encoded here) to run against a real server.`;
  } else if (scheme === "custom-header") {
    // Validate the header name (RFC 7230 token chars). It's interpolated raw into the
    // generated file's `//` hint, so a value with a newline/space would break the
    // comment into invalid TypeScript — fall back to the safe default instead.
    const raw = opts.headerName ?? "X-Api-Key";
    const header = /^[A-Za-z0-9!#$%&'*+.^_`|~-]+$/.test(raw) ? raw : "X-Api-Key";
    credLine = `  headers: { ${JSON.stringify(header)}: ${tokenExpr} },`;
    hint = `// Set ${opts.urlEnv} + ${opts.tokenEnv} (sent as the ${header} header) to run against a real server.`;
  } else if (scheme === "github-app") {
    // GitHub App auth: mint a fine-grained, short-lived installation token from
    // GITHUB_APP_ID / GITHUB_APP_PRIVATE_KEY / GITHUB_APP_ORG at call time — NOT a
    // long-lived <PREFIX>_MCP_TOKEN. `getInstallationToken` resolves the org's
    // installation and returns the raw token string; `getToken` wraps it in { token }.
    imports += `\nimport { getInstallationToken, readGithubAppEnv } from "@deskmate/core/coding";`;
    header = "// Generated by `deskmate mcp-add`. App-authed (mints a GitHub App installation token).";
    credLine =
      `  auth: { getToken: async () => {\n` +
      `    const app = readGithubAppEnv();\n` +
      `    if (!app.present) throw new Error(${JSON.stringify(opts.name)} + ": GITHUB_APP_ID / GITHUB_APP_PRIVATE_KEY required.");\n` +
      `    return { token: await getInstallationToken({ appId: app.appId, privateKey: app.privateKey, org: app.org }) };\n` +
      `  } },`;
    hint = `// Set ${opts.urlEnv} + GITHUB_APP_ID / GITHUB_APP_PRIVATE_KEY / GITHUB_APP_ORG (App with the needed write scope) to run against a real server.`;
  } else {
    credLine = `  auth: { getToken: async () => ({ token: ${tokenExpr} }) },`;
    hint = `// Set ${opts.urlEnv} + ${opts.tokenEnv} to run against a real server, then redeploy.`;
  }

  return `${imports}

${header}
${hint}
export default defineMcpClientConnection({
  url: ${url},
  description: ${JSON.stringify(opts.description)},
${credLine}
  tools: { allow: [${allow}] },
});
`;
}

export type ConnectTemplateOptions = {
  name: string;
  connector: string; // Vercel Connect connector UID, e.g. "vercel/deskmate"
  url: string; // the MCP runtime endpoint, e.g. "https://mcp.vercel.com"
  description: string;
  tools: string[];
};

/** Pure: render an app-scoped Vercel Connect (OAuth) MCP connection. */
export function renderConnectConnection(opts: ConnectTemplateOptions): string {
  const allow = opts.tools.map((t) => JSON.stringify(t)).join(", ");
  return `import { connect } from "@vercel/connect/eve";
import { defineMcpClientConnection } from "eve/connections";

// Generated by \`deskmate mcp-add\` (oauth). App-scoped Vercel Connect: the deskmate
// acts as itself (non-interactive). Provision the connector with \`deskmate connect ${opts.name}\`.
export default defineMcpClientConnection({
  url: ${JSON.stringify(opts.url)},
  description: ${JSON.stringify(opts.description)},
  auth: connect({ connector: ${JSON.stringify(opts.connector)}, principalType: "app" }),
  tools: { allow: [${allow}] },
});
`;
}
