import { describe, it, expect } from "vitest";
import type { TeamConfig } from "@deskmate/core";
import {
  BANNER,
  renderRootAgent,
  renderRosterRegistry,
  renderChannelRoutes,
  renderSubagentAgent,
  renderReexport,
  renderSlackChannel,
  renderSlackAmbientChannel,
  renderDeskmateSaysTool,
  renderFrontDeskInstructions,
  renderSubagentInstructions,
  renderEnvExample,
  renderStubConnection,
  renderDeskmateSweepSchedule,
  renderMemoryTool,
  renderMemoryInstructions,
  renderMemoryReflectionSchedule,
  renderCodingSandbox,
  renderCodingTool,
  renderCodingInstructions,
  renderGithubChannel,
} from "../src/sync/render.js";

// A minimal, hand-built TeamConfig fixture (two deskmates, two mcp connections).
// We build it as a plain object cast to TeamConfig so the renderers stay unit
// testable without importing/parsing a real config file.
const fixtureTeam = {
  model: "anthropic/claude-opus-4.6",
  frontDesk: { maxTurns: 4 },
  connections: {
    sentry: { kind: "mcp", env: "SENTRY" },
    mixpanel: { kind: "mcp", env: "MIXPANEL" },
    vercel: { kind: "mcp", connect: "vercel/deskmate", service: "mcp.vercel.com" },
    ledger: { kind: "tool", from: "./ledger.js" },
  },
  deskmates: {
    devops: {
      role: "devops",
      emoji: ":wrench:",
      displayName: "DevOps Engineer",
      summary: "Triages incidents.",
      reads: ["sentry"],
    },
    product_analyst: {
      role: "product_analyst",
      emoji: ":bar_chart:",
      displayName: "Product Analyst",
      summary: "Turns usage data into a narrative.",
      reads: ["mixpanel"],
    },
  },
  channels: {},
} as unknown as TeamConfig;

describe("BANNER", () => {
  it("names the command and the source of truth", () => {
    expect(BANNER).toContain("GENERATED by");
    expect(BANNER).toContain("deskmate sync");
    expect(BANNER).toContain("deskmate.config.ts");
  });
});

describe("renderRootAgent", () => {
  it("emits a defineAgent with the team model + the banner", () => {
    const out = renderRootAgent(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { defineAgent } from "eve";');
    expect(out).toContain('model: "anthropic/claude-opus-4.6"');
    expect(out).toContain("export default defineAgent(");
  });

  it("keeps @deskmate/core external so channels don't bundle it", () => {
    const out = renderRootAgent(fixtureTeam);
    expect(out).toContain('build: { externalDependencies: ["@deskmate/core"] }');
  });
});

describe("renderSubagentAgent", () => {
  it("wires defineDeskmate(team, id) with the core + config imports", () => {
    const out = renderSubagentAgent("devops");
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { defineDeskmate } from "@deskmate/core";');
    expect(out).toContain('import team from "../../../deskmate.config.js";');
    expect(out).toContain('export default defineDeskmate(team, "devops");');
  });
});

describe("renderRosterRegistry", () => {
  it("emits a DESKMATES Roster const with one entry per deskmate", () => {
    const out = renderRosterRegistry(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import type { Roster } from "@deskmate/core";');
    expect(out).toContain("export const DESKMATES: Roster = {");
    expect(out).toContain("devops:");
    expect(out).toContain("product_analyst:");
    expect(out).toContain('"displayName":"DevOps Engineer"');
    expect(out).toContain('"emoji":":bar_chart:"');
  });

  it("sets providers to the deskmate's reads", () => {
    const out = renderRosterRegistry(fixtureTeam);
    expect(out).toContain('"providers":["sentry"]');
    expect(out).toContain('"providers":["mixpanel"]');
  });
});

describe("renderReexport", () => {
  it("re-exports the default from the given specifier", () => {
    const out = renderReexport("../../../../roles/devops/tools/x.js");
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('export { default } from "../../../../roles/devops/tools/x.js";');
    expect(out).not.toContain("export *");
  });

  it("also re-exports named bindings when star is set", () => {
    const out = renderReexport("../x.js", { star: true });
    expect(out).toContain('export { default } from "../x.js";');
    expect(out).toContain('export * from "../x.js";');
  });
});

describe("channel + tool shims", () => {
  it("slack channel shim calls createSlackChannel with the config maxTurns arg", () => {
    const out = renderSlackChannel(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { createSlackChannel } from "@deskmate/core/channels/slack";');
    expect(out).toContain('import { DESKMATES } from "../lib/deskmates.js";');
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain("export default createSlackChannel(DESKMATES, CHANNEL_ROUTES, 4);");
  });

  it("slack-ambient shim calls createSlackAmbientChannel with the config maxTurns arg", () => {
    const out = renderSlackAmbientChannel(fixtureTeam);
    expect(out).toContain(
      'import { createSlackAmbientChannel } from "@deskmate/core/channels/slack-ambient";',
    );
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain("export default createSlackAmbientChannel(DESKMATES, CHANNEL_ROUTES, 4);");
  });

  it("deskmate_says tool shim re-exports the core tool", () => {
    const out = renderDeskmateSaysTool();
    expect(out).toContain('export { default } from "@deskmate/core/deskmate-says";');
  });
});

describe("renderChannelRoutes", () => {
  it("emits an empty CHANNEL_ROUTES map when the team has no channels", () => {
    const out = renderChannelRoutes(fixtureTeam);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import type { ChannelRoute } from "@deskmate/core";');
    expect(out).toContain("export const CHANNEL_ROUTES: Record<string, ChannelRoute> = {");
  });

  it("emits one entry per team.channels mapping, preserving deskmate + lock", () => {
    const team = {
      ...fixtureTeam,
      channels: {
        C0INCIDENTS: { deskmate: "devops", lock: true },
        C0GROWTH: { deskmate: "product_analyst" },
      },
    } as unknown as TeamConfig;
    const out = renderChannelRoutes(team);
    expect(out).toContain('"C0INCIDENTS": {"deskmate":"devops","lock":true}');
    expect(out).toContain('"C0GROWTH": {"deskmate":"product_analyst"}');
  });

  it("serializes the watch block deterministically", () => {
    const team = {
      ...fixtureTeam,
      channels: { C0INC: { deskmate: "devops", lock: true, watch: { react: true, reply: true, post: false, picker: "routed" } } },
    } as unknown as TeamConfig;
    const out = renderChannelRoutes(team);
    expect(out).toContain('"C0INC": {"deskmate":"devops","lock":true,"watch":{"react":true,"reply":true,"post":false,"picker":"routed"}}');
  });

  it("omits watch when the route has none", () => {
    const team = { ...fixtureTeam, channels: { C0G: { deskmate: "product_analyst" } } } as unknown as TeamConfig;
    expect(renderChannelRoutes(team)).toContain('"C0G": {"deskmate":"product_analyst"}');
  });
});

describe("renderFrontDeskInstructions", () => {
  it("prepends a generated banner to the core front-desk prose", () => {
    const out = renderFrontDeskInstructions();
    expect(out).toContain("GENERATED by");
    expect(out).toContain("# Identity");
    expect(out).toContain("# Convening multiple deskmates");
    expect(out).toContain("deskmate_says");
  });

  it("tells the front desk to keep follow-ups with the same deskmate", () => {
    const out = renderFrontDeskInstructions().toLowerCase();
    expect(out).toContain("follow-up");
    expect(out).toContain("same deskmate");
  });
});

describe("renderSubagentInstructions", () => {
  const role = "# Role: DevOps\nAuthored, verbatim.\n";

  it("keeps the authored role instructions, then appends the house style", () => {
    const out = renderSubagentInstructions(role);
    expect(out.startsWith("# Role: DevOps")).toBe(true);
    expect(out).toContain("Authored, verbatim.");
    expect(out).toContain("## How you write");
    expect(out).toContain("## Grounding and clarifying");
  });

  it("adds a voice section only when a voice line is given", () => {
    expect(renderSubagentInstructions(role)).not.toContain("## Your voice");
    const out = renderSubagentInstructions(role, "Terse SRE. Dry, not chatty.");
    expect(out).toContain("## Your voice");
    expect(out).toContain("Terse SRE. Dry, not chatty.");
  });

  it("ends with exactly one trailing newline (deterministic)", () => {
    expect(renderSubagentInstructions(role)).toMatch(/[^\n]\n$/);
  });
});

describe("renderEnvExample", () => {
  it("emits URL + TOKEN vars for each mcp connection env prefix", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).toContain("SENTRY_MCP_URL=");
    expect(out).toContain("SENTRY_MCP_TOKEN=");
    expect(out).toContain("MIXPANEL_MCP_URL=");
    expect(out).toContain("MIXPANEL_MCP_TOKEN=");
  });

  it("skips non-mcp connections", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("LEDGER_MCP_URL=");
  });

  it("does NOT seed DESKMATE_MAX_TURNS (it would override frontDesk.maxTurns)", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("DESKMATE_MAX_TURNS");
  });

  it("lists oauth connections in a Vercel Connect block, without URL/TOKEN vars", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("VERCEL_MCP_URL=");
    expect(out).not.toContain("VERCEL_MCP_TOKEN=");
    expect(out).toContain("OAuth connections (Vercel Connect)");
    expect(out).toContain("vercel");
    expect(out).toContain("vercel/deskmate");
    expect(out).toContain("deskmate connect vercel");
  });

  it("omits DATABASE_URL when no deskmate opts into memory", () => {
    const out = renderEnvExample(fixtureTeam);
    expect(out).not.toContain("DATABASE_URL");
  });

  it("surfaces DATABASE_URL (commented) when a deskmate opts into memory", () => {
    const withMemory = {
      ...fixtureTeam,
      deskmates: {
        ...fixtureTeam.deskmates,
        product_analyst: { ...fixtureTeam.deskmates.product_analyst, memory: { maxItems: 200, coreLimit: 25 } },
      },
    } as unknown as TeamConfig;
    const out = renderEnvExample(withMemory);
    expect(out).toContain("# DATABASE_URL=postgres://...");
    expect(out).toContain("ephemeral in-memory");
  });
});

describe("renderDeskmateSweepSchedule", () => {
  it("renders a schedule that calls createDeskmateSweep with the configured cron", () => {
    const out = renderDeskmateSweepSchedule({ ...fixtureTeam, sweep: { cron: "0 8 * * 1-5" } } as any);
    expect(out).toContain('import { createDeskmateSweep } from "@deskmate/core";');
    expect(out).toContain('import { DESKMATES } from "../lib/deskmates.js";');
    expect(out).toContain('import { CHANNEL_ROUTES } from "../lib/channel-routes.js";');
    expect(out).toContain('import slack from "../channels/slack.js";');
    expect(out).toContain('createDeskmateSweep(DESKMATES, CHANNEL_ROUTES, { cron: "0 8 * * 1-5", slack })');
  });
  it("falls back to the default cron when sweep is omitted", () => {
    const out = renderDeskmateSweepSchedule(fixtureTeam);
    expect(out).toContain('"0 9 * * 1-5"');
  });
});

describe("renderMemoryTool", () => {
  it("re-exports one tool off createMemoryTools(id), bound to the deskmate id", () => {
    for (const tool of ["remember", "recall", "forget"] as const) {
      const out = renderMemoryTool("devops", tool);
      expect(out.startsWith(BANNER)).toBe(true);
      expect(out).toContain('import { createMemoryTools } from "@deskmate/core/memory";');
      expect(out).toContain(`export default createMemoryTools("devops").${tool};`);
    }
  });

  it("ends with exactly one trailing newline (deterministic)", () => {
    expect(renderMemoryTool("devops", "remember")).toMatch(/[^\n]\n$/);
  });
});

describe("renderMemoryInstructions", () => {
  it("wires createMemoryInstructions(id, coreLimit) with the numeric coreLimit", () => {
    const out = renderMemoryInstructions("devops", 12);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain('import { createMemoryInstructions } from "@deskmate/core/memory";');
    expect(out).toContain('export default createMemoryInstructions("devops", 12);');
  });
});

describe("renderMemoryReflectionSchedule", () => {
  it("wires createMemoryReflection with the ids, an awaited store, and the imported default cron", () => {
    const out = renderMemoryReflectionSchedule(["devops", "product_analyst"]);
    expect(out.startsWith(BANNER)).toBe(true);
    expect(out).toContain(
      'import { createMemoryReflection, resolveMemoryStore, DEFAULT_MEMORY_REFLECT_CRON } from "@deskmate/core/memory";',
    );
    expect(out).toContain(
      'createMemoryReflection(["devops","product_analyst"], await resolveMemoryStore(), { cron: DEFAULT_MEMORY_REFLECT_CRON });',
    );
  });

  it("emits an overriding cron as a JSON string and does not import the unused default", () => {
    const out = renderMemoryReflectionSchedule(["devops"], "30 2 * * *");
    expect(out).toContain('import { createMemoryReflection, resolveMemoryStore } from "@deskmate/core/memory";');
    expect(out).not.toContain("DEFAULT_MEMORY_REFLECT_CRON");
    expect(out).toContain('createMemoryReflection(["devops"], await resolveMemoryStore(), { cron: "30 2 * * *" });');
  });
});

describe("renderStubConnection", () => {
  it("reads env vars via bracket access (valid TS even for a non-identifier prefix)", () => {
    const out = renderStubConnection("weird", { env: "123" });
    expect(out).toContain('process.env["123_MCP_URL"]');
    expect(out).toContain('process.env["123_MCP_TOKEN"]');
    expect(out).not.toContain("process.env.123_MCP_URL");
    expect(out).not.toContain("process.env.123_MCP_TOKEN");
  });

  it("derives the env prefix from the name when none is given, still bracketed", () => {
    const out = renderStubConnection("my_conn", undefined);
    expect(out).toContain('process.env["MY_CONN_MCP_URL"]');
    expect(out).toContain('process.env["MY_CONN_MCP_TOKEN"]');
  });

  it("emits an app-scoped connect() stub for an oauth connection", () => {
    const out = renderStubConnection("vercel", { connect: "vercel/deskmate", service: "mcp.vercel.com" });
    expect(out).toContain('import { connect } from "@vercel/connect/eve";');
    expect(out).toContain('auth: connect({ connector: "vercel/deskmate", principalType: "app" })');
    expect(out).not.toContain("process.env");
    expect(out).toContain("deskmate connect vercel");
  });
});

describe("coding renderers", () => {
  it("renders a sandbox shim bound to the team org + repo allowlist", () => {
    const s = renderCodingSandbox({ org: "acme", repos: ["acme/*"] });
    expect(s).toContain(BANNER);
    expect(s).toContain('from "@deskmate/core/coding"');
    expect(s).toContain("createCodingSandbox");
    expect(s).toContain('"acme"');
    expect(s).toContain('"acme/*"'); // repos threaded through for read-token scoping
  });

  it("renders the open_pull_request tool shim bound to id/org/repos", () => {
    const t = renderCodingTool("engineer", { org: "acme", repos: ["acme/*"] });
    expect(t).toContain("createOpenPullRequestTool");
    expect(t).toContain('"engineer"');
    expect(t).toContain('"acme"');
    expect(t).toContain('"acme/*"');
    expect(t).toContain("export default");
  });

  it("renders the static coding instructions module", () => {
    const i = renderCodingInstructions();
    expect(i).toContain('from "eve/instructions"');
    expect(i).toContain("defineInstructions");
    expect(i).toContain("createCodingInstructions");
  });

  it("renders the root github channel shim", () => {
    const c = renderGithubChannel();
    expect(c).toContain(BANNER);
    expect(c).toContain('from "eve/channels/github"');
    expect(c).toContain("githubChannel()");
    expect(c).toContain("export default");
  });

  it("includes GITHUB_APP_* in .env.example only when a deskmate has coding", () => {
    const withCoding = {
      ...fixtureTeam,
      github: { org: "acme" },
      deskmates: {
        eng: {
          role: "engineer",
          emoji: ":technologist:",
          displayName: "Software Engineer",
          summary: "s",
          reads: [],
          coding: { repos: ["acme/*"] },
        },
      },
    } as unknown as TeamConfig;
    const s = renderEnvExample(withCoding);
    expect(s).toContain("GITHUB_APP_ID");
    expect(s).toContain("GITHUB_APP_PRIVATE_KEY");
    expect(s).toContain("GITHUB_APP_ORG=acme");
    expect(s).toContain("GITHUB_WEBHOOK_SECRET");
    expect(s).toContain("GITHUB_TOKEN"); // commented local-only fallback
    expect(s).not.toContain("GITHUB_APP_SLUG"); // slug is channel-only, no channel here
    // the GITHUB_TOKEN comment line must not carry a stray template backtick
    expect(s.split("\n").find((l) => l.includes("GITHUB_TOKEN"))?.trimEnd().endsWith("`")).toBe(false);

    expect(renderEnvExample(fixtureTeam)).not.toContain("GITHUB_APP_ID");
  });

  it("scaffolds GITHUB_APP_SLUG + the App env when the github channel is enabled", () => {
    const channelOnly = { ...fixtureTeam, github: { org: "acme", channel: true } } as unknown as TeamConfig;
    const s = renderEnvExample(channelOnly);
    expect(s).toContain("GITHUB_APP_ID");
    expect(s).toContain("GITHUB_WEBHOOK_SECRET");
    expect(s).toContain("GITHUB_APP_SLUG"); // needed for @mention dispatch
  });
});

import { renderJobSchedule, renderHooksChannel } from "../src/sync/render.js";

const spec = {
  jobId: "conversation_review",
  deskmate: "product_analyst",
  displayName: "Product Analyst",
  brief: "Read yesterday's conversations.\nReport what broke.",
  ceiling: "issue" as const,
  maxItems: 3,
  window: "24h",
};

describe("renderJobSchedule", () => {
  const out = renderJobSchedule({ jobId: "conversation_review", cron: "0 6 * * *", channelId: "C0123", job: spec });

  it("carries the generated banner", () => {
    expect(out.startsWith("// GENERATED by `deskmate sync`")).toBe(true);
  });
  it("imports the factory from the core jobs subpath", () => {
    expect(out).toContain('import { createJobSchedule } from "@deskmate/core/jobs";');
    expect(out).toContain('import slack from "../channels/slack.js";');
  });
  it("passes the cron and the resolved channel id", () => {
    expect(out).toContain('cron: "0 6 * * *"');
    expect(out).toContain('channelId: "C0123"');
  });
  it("JSON-encodes a multi-line brief so it cannot break the file", () => {
    expect(out).toContain('"brief": "Read yesterday\'s conversations.\\nReport what broke."');
    expect(out).not.toContain("\n    Report what broke.");
  });
  it("survives a brief containing backticks and template syntax", () => {
    const nasty = renderJobSchedule({
      jobId: "j", cron: "0 6 * * *", channelId: "C0",
      job: { ...spec, brief: "use `sql` and ${danger}" },
    });
    // JSON.stringify emits a DOUBLE-quoted string, where a backtick and a ${} are
    // both inert — which is exactly why the brief is encoded rather than templated.
    expect(nasty).toContain('"brief": "use `sql` and ${danger}"');
  });
});

describe("renderHooksChannel", () => {
  const out = renderHooksChannel({
    feedback_triage: { ...spec, jobId: "feedback_triage", window: undefined, channelId: "C0SUCCESS" },
  });

  it("imports the hooks factory and the slack channel", () => {
    expect(out).toContain('import { createHooksChannel } from "@deskmate/core/jobs";');
    expect(out).toContain('import slack from "../channels/slack.js";');
  });
  it("embeds each job keyed by id", () => {
    expect(out).toContain('"feedback_triage"');
    expect(out).toContain('"channelId": "C0SUCCESS"');
  });
});
